import localFont from "next/font/local";
import "./globals.css";
import LoginForm from '@/components/LoginForm';
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CBL",
  description: "Generated by Jahaann",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        {children}        
      </body>
    </html>
  );
}